import { GoogleGenAI } from "@google/genai";
import { GEMINI_MODEL } from "../constants";

export const generateEditedImage = async (
  sourceImageBase64: string,
  sourceMimeType: string,
  prompt: string,
  styleImageBase64?: string,
  styleMimeType?: string
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing. Please set process.env.API_KEY.");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const parts: any[] = [];

  // Add Source Image
  parts.push({
    inlineData: {
      data: sourceImageBase64,
      mimeType: sourceMimeType,
    },
  });

  // Add Style Image if present
  if (styleImageBase64 && styleMimeType) {
    parts.push({
      inlineData: {
        data: styleImageBase64,
        mimeType: styleMimeType,
      },
    });
  }

  // Add Text Prompt
  parts.push({
    text: prompt,
  });

  try {
    const response = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: {
        parts: parts,
      },
    });

    // Extract image from response
    if (response.candidates && response.candidates.length > 0) {
      const content = response.candidates[0].content;
      if (content && content.parts) {
        for (const part of content.parts) {
          if (part.inlineData && part.inlineData.data) {
            return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
          }
        }
      }
    }

    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
